version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resimhub-backend
    command: uvicorn backend.fastapi_app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - envs/.env
    depends_on:
      - redis
    networks:
      - resimhub-net

  redis:
    image: redis:7
    container_name: resimhub-redis
    ports:
      - "6379:6379"
    networks:
      - resimhub-net

networks:
  resimhub-net:
    driver: bridge
